### ISSUE TITLE
Add cohab data

### ISSUE THREAD

**Issue by mbojan** [statnet/statnet.data#5]
Add `cohab` data. Where can I get it @drh20drh20 ?

**Comment by drh20drh20** [comment]
[cohab.RData.zip](https://github.com/statnet/statnet.data/files/6625227/cohab.RData.zip)

@mbojan the `.RData` file is attached here.  I have a doc file that's nearly ready to go but needs some tweaking that I can do by, say, 5 hours from now.  The doc file is in the form of a `roxygenize`-able insert to the `R/data.R` file—is this correct or should the doc file be in some different format?

**Comment by mbojan** [comment]
Thanks @drh20drh20 !

The goal is to move all the data from statnet packages into this one, but I won't be able to make it for the release @krivit  is preparing atm. If you are determined to have `cohab` in current release we have to put it into `ergm`. I'll move it to `statnet.data` later. All in all, no real rush with putting `cohab` here.

**Comment by drh20drh20** [comment]
Got it.  I'd say that "determined" is too strong a word, but it seems that there's no cost to pushing `cohab` into `ergm` now, then `statnet.data` later.  There is a small bonus to getting it into one or the other soon so that when we submit a revised version of our ergm 4.0 paper we can simply use `data(cohab)` instead of needing to supply the supplemental `cohab.RData` file.
